### ISSUE TITLE
can not run FaceWarperServer

### ISSUE THREAD

**Issue by WANGRuoxi233** [joelmoniz/DepthNets#14]

**Comment by WANGRuoxi233** [comment]
Hello! I built FaceWarperServer as you said in readme, but I found it didn't work(Segmentation fault).

I built FaceWarperServer in a Linux server. When I ran build_linux.sh, some log information was printed as follow. There is no information about glm.
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.54") 
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GLUT: /usr/lib/x86_64-linux-gnu/libglut.so  
-- Found GLEW: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wrx/workplace/DepthNets/FaceWarper/FaceWarperServer/build

**Comment by srajotte** [comment]
What Linux distribution and version are you using?
Your problem seems similar to issue #9 that was previously reported. Could you read the issue and see if it applies to your situation?

**Comment by WANGRuoxi233** [comment]
> What Linux distribution and version are you using?
> Your problem seems similar to issue #9 that was previously reported. Could you read the issue and see if it applies to your situation?

Actually，I realized it yesterday，and fixed the issue by changing “set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")” to "set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -pthread")". However, I have a new problem now. When I run FaceWarperServer, I get a error as follow:
 freeglut (./FaceWarperServer):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow
This seems to be a problem that comes up with remote configurations.
My linux server is Ubuntu 16.04.2, and I use Xshell to connect it. Moreover, Xmanger support local X11 display，and I can get a window in local when I excute "Dispaly xxx.jpg".
Could you tell me the correct result of run FaceWarpServer ? Does it generate a window?

**Comment by srajotte** [comment]
FaceWarperServer does open a window. 

Unfortunately, I don't have a setup where I can test remote execution and I have no experience running an OpenGL application over remote X11

**Comment by WANGRuoxi233** [comment]
> FaceWarperServer does open a window.
> 
> Unfortunately, I don't have a setup where I can test remote execution and I have no experience running an OpenGL application over remote X11

It's doesn't matter. I will try to solve it by myself. 
Anyway,thank u for your help and patience.

**Comment by srajotte** [comment]
No problem.
I will keep the issue open. If you find a solution to your problem, it would be appreciated if you could add an explanation here.

**Comment by WANGRuoxi233** [comment]
I solved my problem by using local display，it seems that openGL doesn‘t support remote display（Maybe it support，but I don’t know how to use). 
By the way, did you provide any test code for us in cyclegan part? I only see the training code. @srajotte
