### ISSUE TITLE
set conda env failed

### ISSUE THREAD

**Issue by wx176** [joelmoniz/DepthNets#8]
Hello! Great job! 
I am very interested about your work. However, i met a issue in the first step.
![screenshot from 2018-12-11 17-02-05](https://user-images.githubusercontent.com/8123192/49789346-b8940500-fd66-11e8-9b18-c221aa001576.png)

**Comment by christopher-beckham** [comment]
Hi,

Good spotting! Not sure how this got past my testing. It looks like the mkl version (2019.0) is too new for mkl_fft. Could you remote the line `- mkl==2019.0=118` from `environment.yml` and re-create the conda environment and see if that fixes the issue?

If it does, I'll commit the fix.

**Comment by wx176** [comment]
Hi! Sorry for the late reply!
The issue was gone after i removed that line. Cheers！
